# -*- coding: utf-8 -*-
"""Modelo_IA_Roupas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Prizrak2/Modelo-IA-Roupas/blob/main/Modelo_IA_Roupas.ipynb
"""

#imports
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

#carregando dados
dataset = keras.datasets.fashion_mnist
((imagens_treino, identificacoes_treino),(imagens_teste, identificacoes_teste)) = dataset.load_data()

#classificando dados
total_de_classificacoes = 10
nomes_de_classificacoes = ['Camiseta', 'Calca', 'Suéter', 'Vestido', 'Casaco', 'Sandalia', 'Camisa', 'Tênis', 'Bolsa', 'Bota']

imagens_treino = imagens_treino/float(255)
modelo = keras.Sequential([
    #entrada
    keras.layers.Flatten(input_shape = (28,28)),
    #oculta-
    keras.layers.Dense(256, activation=tf.nn.relu),
    keras.layers.Dropout(0.2),
    #saida
    keras.layers.Dense(10, activation=tf.nn.softmax)
])

modelo.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

historico = modelo.fit(imagens_treino, identificacoes_treino, epochs=50, validation_split=0.2)

plt.plot(historico.history['accuracy'])
plt.plot(historico.history['val_accuracy'])
plt.title('Acuracia do modelo')
plt.xlabel('Epocas')
plt.ylabel('Acuracia')
plt.legend(['treino', 'validacao'])

plt.plot(historico.history['loss'])
plt.plot(historico.history['val_loss'])
plt.title('Perda do modelo')
plt.xlabel('Epocas')
plt.ylabel('Perda')
plt.legend(['treino', 'validacao'])

perda_teste, acuracia_teste = modelo.evaluate(imagens_teste, identificacoes_teste)
print('Perda do teste: ', perda_teste)
print('Acuracia do teste: ', acuracia_teste)